# Generated by Django 5.1.4 on 2024-12-30 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postmodel_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoriamodel'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subcategoriamodel'),
        ),
        migrations.AddField(
            model_name='subcategoriamodel',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoriamodel'),
        ),
    ]
